export const signupFormFields = [
  {
    label: "First Name",
    name: "firstName",
    type: "text",
    placeholder: "Enter your first name",
    required: true,
  },
  {
    label: "Last Name",
    name: "lastName",
    type: "text",
    placeholder: "Enter your last name",
    required: true,
  },
  {
    label: "Address",
    name: "address",
    type: "text",
    placeholder: "Enter your address",
    required: true,
  },
  {
    label: "Phone",
    name: "phone",
    type: "tel",
    placeholder: "Enter your phone number",
    required: true,
  },
  {
    label: "Email",
    name: "email",
    type: "email",
    placeholder: "Enter your email",
    required: true,
  },
  {
    label: "Password",
    name: "password",
    type: "password",
    placeholder: "Enter your password",
    required: true,
  },
  {
    label: "Confirm Password",
    name: "confirmPassword",
    type: "password",
    placeholder: "Re-Enter your password",
    required: true,
  },
];
